#SwapUnina Configuration - Encrypted
#Tue Feb 24 19:33:48 CET 2026
app.name=SwapUnina-App
app.version=2.0
db.host=localhost
db.name=postgres
db.password=
db.pool.connection_timeout=30000
db.pool.idle_timeout=600000
db.pool.max_lifetime=1800000
db.pool.max_size=10
db.pool.min_idle=2
db.port=5432
db.timeout.connection=5
db.timeout.socket=30
db.user=postgres
test.prop=test-value
