app.name=SwapUnina-App-H2
app.version=2.0
db.url=jdbc:h2:mem:swapunina;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
db.driver=org.h2.Driver
db.name=swapunina
db.user=sa
db.password=
db.pool.connection_timeout=30000
db.pool.idle_timeout=600000
db.pool.max_lifetime=1800000
db.pool.max_size=10
db.pool.min_idle=2
